name: Validate VitePress Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: |
        npm install
        npm install -g vitepress@1.6.3

    - name: Build VitePress site
      run: |
        npm run docs:build -- --force > build_output.log 2>&1
        echo "--- Build Output ---"
        cat build_output.log
        echo "--- End of Build Output ---"
      continue-on-error: true

    - name: Check for build errors
      run: |
        if grep -q "Build failed" build_output.log; then
          echo "Build errors found. See the build output above for details."
          exit 1
        else
          echo "Build completed successfully."
        fi
