name: Build, Push, and Notify Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: |
          turbo.azurecr.io/docs:${{ steps.date.outputs.date }}.${{ github.run_number }}
          turbo.azurecr.io/docs:latest

    - name: Login to Azure Container Registry
      if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master'
      uses: azure/docker-login@v1
      with:
        login-server: turbo.azurecr.io
        username: ${{ secrets.TURBO_REGISTRY_APP_ID }}
        password: ${{ secrets.TURBO_REGISTRY_APP_PASSWORD }}

    - name: Push Docker image
      if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master'
      run: |
        docker push turbo.azurecr.io/docs:${{ steps.date.outputs.date }}.${{ github.run_number }}
        docker push turbo.azurecr.io/docs:latest

    - name: Notify Private Repo
      if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.CODESYSTEMS_PAT }}
        repository: codesystems/turbonet
        event-type: public-docs-update
        client-payload: '{"version": "docs:${{ steps.date.outputs.date }}.${{ github.run_number }}"}'
