name: Validate VitePress Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: |
        npm install
        npm install -g vitepress@1.6.3

    - name: Build VitePress site
      run: |
        vitepress build src --no-exit || true
        if [ ! -d "src/.vitepress/dist" ]; then
          echo "Build failed. Output directory does not exist."
          exit 1
        fi

    - name: Display build errors
      run: |
        echo "Checking for build errors..."
        
        if [ -f "src/.vitepress/logs/error.log" ]; then
          echo "VitePress Error Log:"
          cat src/.vitepress/logs/error.log
          BUILD_FAILED=true
        fi
        
        if [ -f "npm-debug.log" ]; then
          echo "NPM Debug Log:"
          cat npm-debug.log
          BUILD_FAILED=true
        fi
        
        if [ "$BUILD_FAILED" = true ]; then
          echo "Errors were found during the build process. Check the logs above for details."
          exit 1
        else
          echo "Build completed successfully with no errors."
        fi
