name: Notify Private Docs Deploy Workflow

on:
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CODESYSTEMS_PAT }}
          repository: codesystems/turbonet
          event-type: public-docs-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
